apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: flask-app-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: flask-app-repo
  policy:
    semver:
      range: ">=1.0.0"