apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flask-app  # 🔹 Ensure this name matches `flux get kustomizations`
  namespace: flux-system
spec:
  interval: 1m
  path: ./k8s/base  # 🔹 Ensure this path is correct
  prune: true
  sourceRef:
    kind: GitRepository
    name: flask-app  # 🔹 Ensure this matches `git-repository.yaml`
  targetNamespace: python-web-app-ns