apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flask-app
  namespace: flux-system
spec:
  interval: 5m
  path: ./k8s/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: flask-app
  target:
    namespace: python-web-app-ns 