apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flask-app
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/Mossaaba/flux-pyth
  ref:
    branch: main